spring:
    application:
        name: demo
    datasource:
        url: jdbc:h2:mem:demodb;DB_CLOSE_DELAY=-1
        driver-class-name: org.h2.Driver
        username: sa
        password: 
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate.ddl-auto: none 
        defer-datasource-initialization: true
    h2:
        console:
            enabled: true
            path: /h2-console
    sql:
        init:
            schema-locations: classpath:sql/schema.sql
            data-locations: classpath:sql/data.sql
server:
    port: 9091

logging:
    level:
        '[org.springframework.test.web]': DEBUG
